name: SSH Build

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Show my IP
        run: curl -s ifconfig.me && echo ""

      - name: Start SSH via tmate
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 360
